service: sambhram-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION} # Make sure AWS_REGION is set in your environment variables
  environment:
    MONGO_URL: ${env:MONGO_URL}
    RAZORPAY_KEY_ID: ${env:RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${env:RAZORPAY_KEY_SECRET}
    RAZORPAY_WEBHOOK_SECRET: ${env:RAZORPAY_WEBHOOK_SECRET}
    AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}

functions:
  app:
    handler: app.handler  # Ensure `app.js` is the entry point and `handler` is the function export
    events:
      - httpApi: '*'  # This will route all HTTP paths to this Lambda

package:
  patterns:
    - '!node_modules/**'  # Exclude node_modules to minimize package size
    - '!tests/**'         # Exclude test files if not needed in production
    - '**'                # Include all other project files

plugins:
  - serverless-dotenv-plugin # To use environment variables from .env

