name: Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify your Node.js version here

      - name: Install Dependencies
        run: |
          npm install
          npm prune --production # Keep only production dependencies if necessary

      - name: Create ZIP file for Lambda function
        run: zip -r code.zip . -x ".git/*" # Include node_modules in the ZIP

      - name: Deploy to AWS Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: |
            lambda update-function-code
            --function-name arn:aws:lambda:us-east-1:577638369990:function:sambhram-backend
            --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
